book_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

dog_eared_books/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, create_book_entry, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, edit_book, delete_book, add_book_entry_ajax, create_book_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-book-entry', create_book_entry, name='create_book_entry'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-book/<uuid:id>', edit_book, name='edit_book'),
    path('delete/<uuid:id>', delete_book, name='delete_book'),
    path('create-book-entry-ajax', add_book_entry_ajax, name='add_book_entry_ajax'),
    path('create-flutter/', create_book_flutter, name='create_book_flutter'),
]

main/models.py
import uuid 
from django.db import models
from django.contrib.auth.models import User

class BookEntry(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False) 
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    price = models.IntegerField()
    genre =  models.CharField(max_length=100)
    summary = models.TextField()

main/forms.py
from django.forms import ModelForm
from main.models import BookEntry
from django.utils.html import strip_tags

class BookEntryForm(ModelForm):
    class Meta:
        model = BookEntry
        fields = ["title", "author", "price", "genre", "summary"]

    def clean_title(self):
        title = self.cleaned_data["title"]
        return strip_tags(title)

    def clean_author(self):
        author = self.cleaned_data["author"]
        return strip_tags(author)

    def clean_genre(self):
        genre = self.cleaned_data["genre"]
        return strip_tags(genre)
    
    def clean_summary(self):
        summary = self.cleaned_data["summary"]
        return strip_tags(summary)

main/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
from main.forms import BookEntryForm
from main.models import BookEntry
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import datetime
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags
import json


@login_required(login_url='/login')
def show_main(request):

    context = {
        'application_name': 'dog-eared-books',
        'class': 'PBP KKI',
        'name': request.user.username,

        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_book_entry(request):
    form = BookEntryForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        book_entry = form.save(commit=False)
        book_entry.user = request.user
        book_entry.save()
        return redirect('main:show_main')

    context = {'form': form}
    return render(request, "create_book_entry.html", context)

def show_xml(request):
    data = BookEntry.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BookEntry.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BookEntry.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = BookEntry.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            user = form.get_user()
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.error(request, "Invalid username or password. Please try again.")

    else:
        form = AuthenticationForm(request)
    context = {'form': form}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_book(request, id):
    book = BookEntry.objects.get(pk = id)

    form = BookEntryForm(request.POST or None, instance=book)

    if form.is_valid() and request.method == "POST":
        # Save form and return to home page
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_book.html", context)

def delete_book(request, id):
    # Get book based on id
    book = BookEntry.objects.get(pk = id)
    # Delete book
    book.delete()
    # Return to home page
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
@require_POST
def add_book_entry_ajax(request):
    title = strip_tags(request.POST.get("title"))
    author = strip_tags(request.POST.get("author"))
    price = request.POST.get("price")
    genre = strip_tags(request.POST.get("genre"))
    summary = strip_tags(request.POST.get("summmary"))
    user = request.user

    new_book = BookEntry(
        title=title, 
        author=author,
        price=price,
        genre=genre,
        summary=summary,
        user=user
    )
    new_book.save()

    return HttpResponse(b"CREATED", status=201)

@csrf_exempt
def create_book_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        new_mood = BookEntry.objects.create(
            user=request.user,
            title=data["title"],
            author=data["author"],
            genre=data["genre"],
            summary=data["summary"],
            price=int(data["price"]),
        )

        new_mood.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/card_book.html
<div class="relative w-64 h-80 bg-white shadow-lg rounded-lg mb-2 border-2 border-gray-300 overflow-hidden flex transform hover:scale-105 hover:shadow-2xl transition-all duration-300">
    <!-- left side -->
    <div class="w-1/5 bg-green-900 text-white p-4 flex flex-col justify-center rounded-l-lg">
    </div>
  
    <!-- right side -->
    <div class="p-4 flex-1 bg-gray-50 rounded-r-lg flex flex-col">
      <!-- book title -->
      <h3 class="font-bold text-xl text-gray-800 mb-1">{{ book_entry.title }}</h3>
      <!-- book author -->
      <p class="text-gray-600 italic mb-2">by {{ book_entry.author }}</p>
      <!-- book genre -->
      <p class="text-green-700 font-semibold mb-1">Genre: {{ book_entry.genre }}</p>
      <!-- book price -->
      <p class="text-green-600 font-bold mb-3">Price: ${{ book_entry.price }}</p>
      
      <!-- book summary -->
      <p class="text-gray-700 flex-grow overflow-scroll whitespace-normal text-sm">
        {{ book_entry.summary }}
      </p>
  
      <!-- edit and delete buttons  -->
      <div class="flex justify-end space-x-2 mt-2">
        <a href="{% url 'main:edit_book' book_entry.pk %}" class="bg-red-700 hover:bg-yellow-600 text-white rounded-full p-2 transition duration-300 shadow-md">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
          </svg>
        </a>
        <a href="{% url 'main:delete_book' book_entry.pk %}" class="bg-red-800 hover:bg-red-600 text-white rounded-full p-2 transition duration-300 shadow-md">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
          </svg>
        </a>
      </div>
    </div>
  </div>
  

main/templates/card_info.html
<div class="bg-gradient-to-r from-black to-green-900 shadow-lg rounded-lg overflow-hidden hover:shadow-2xl transition duration-300 ease-in-out transform hover:-translate-y-1">
    <div class="p-4">
      <h5 class="text-lg font-semibold text-white">{{ title }}</h5>
      <p class="text-white">{{ value }}</p>
    </div>
</div>
  

main/templates/create_book_entry.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Create Book</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="min-h-screen bg-[url('{% static "image/aeon7.webp" %}')] bg-cover bg-center bg-fixed flex flex-col">
  <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
    <h1 class="text-3xl font-bold text-center mb-8 text-green-900">Create Book Entry</h1>
  
    <div class="bg-white shadow-md rounded-lg p-6 form-style">
      <form method="POST" class="space-y-6">
        {% csrf_token %}
        {% for field in form %}
          <div class="flex flex-col">
            <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-green-900">
              {{ field.label }}
            </label>
            <div class="w-full">
              {{ field }}
            </div>
            {% if field.help_text %}
              <p class="mt-1 text-sm text-green-900">{{ field.help_text }}</p>
            {% endif %}
            {% for error in field.errors %}
              <p class="mt-1 text-sm text-red-600">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
        <div class="flex justify-center mt-6">
          <button type="submit" class="bg-green-900 text-white font-semibold px-6 py-3 rounded-lg hover:bg-greeen-700 transition duration-300 ease-in-out w-full">
            Create Book Entry
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

main/templates/edit_book.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Edit Book</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class="min-h-screen bg-[url('{% static "image/aeon15.webp" %}')] bg-cover bg-center bg-fixed flex flex-col">
  <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
    <h1 class="text-3xl font-bold text-center mb-8 text-green-900">Edit Book Entry</h1>
  
    <div class="bg-white rounded-lg p-6 form-style">
      <form method="POST" class="space-y-6">
          {% csrf_token %}
          {% for field in form %}
              <div class="flex flex-col">
                  <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-green-900">
                      {{ field.label }}
                  </label>
                  <div class="w-full">
                      {{ field }}
                  </div>
                  {% if field.help_text %}
                      <p class="mt-1 text-sm text-gray-500">{{ field.help_text }}</p>
                  {% endif %}
                  {% for error in field.errors %}
                      <p class="mt-1 text-sm text-red-600">{{ error }}</p>
                  {% endfor %}
              </div>
          {% endfor %}
          <div class="flex justify-center mt-6">
              <button type="submit" class="bg-green-900 text-white font-semibold px-6 py-3 rounded-lg hover:bg-green-900 transition duration-300 ease-in-out w-full">
                  Edit Book Entry
              </button>
          </div>
      </form>
  </div>
  </div>
</div>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<div class="min-h-screen flex items-center justify-center bg-[url('{% static "image/aeon13.webp" %}')] bg-cover bg-center bg-fixed flex flex-col">
  <div class="max-w-md w-full space-y-8">
    <div>
      <h2 class="mt-6 text-center text-white text-3xl font-extrabold text-gray-900">
        Login to your account
      </h2>
    </div>
    <form class="mt-8 space-y-6" method="POST" action="">
      {% csrf_token %}
      <input type="hidden" name="remember" value="true">
      <div class="rounded-md shadow-sm -space-y-px">
        <div>
          <label for="username" class="sr-only">Username</label>
          <input id="username" name="username" type="text" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-green-900 focus:border-green-900 focus:z-10 sm:text-sm" placeholder="Username">
        </div>
        <div>
          <label for="password" class="sr-only">Password</label>
          <input id="password" name="password" type="password" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-green-900 focus:border-green-900 focus:z-10 sm:text-sm" placeholder="Password">
        </div>
      </div>

      <div>
        <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-green-900 hover:bg-green-900 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-900">
          Sign in
        </button>
      </div>
    </form>

    {% if messages %}
    <div class="mt-4">
      {% for message in messages %}
      {% if message.tags == "success" %}
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% elif message.tags == "error" %}
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% else %}
            <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% endif %}
      {% endfor %}
    </div>
    {% endif %}

    <div class="text-center mt-4">
      <p class="text-sm text-white">
        Don't have an account yet?
        <a href="{% url 'main:register' %}" class="font-medium text-green-700 hover:text-green-900">
          Register Now
        </a>
      </p>
    </div>
  </div>
</div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Dog Eared Books</title>
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class="overflow-x-hidden px-4 md:px-8 pb-8 pt-24 min-h-screen bg-[url('{% static "image/aeon3.webp" %}')] bg-cover bg-center bg-fixed flex flex-col">
  <div class="p-2 mb-6 relative">
    <div class="relative grid grid-cols-1 z-30 md:grid-cols-2 gap-8">
      {% include "card_info.html" with title='Name' value=name %}
      {% include "card_info.html" with title='Class' value=class %}
    </div>
    <div class="w-full px-6  absolute top-[44px] left-0 z-20 hidden md:flex">
      <div class="w-full min-h-4 bg-green-900"></div>
    </div>
    <div class="h-full w-full py-6  absolute top-0 left-0 z-20 md:hidden flex ">
      <div class="h-full min-w-4 bg-green-900 mx-auto"></div>
    </div>
  </div>

  <div class="px-3 mb-4">
    <div class="flex rounded-md items-center bg-green-900 py-2 px-4 w-fit">
      <h1 class="text-white text-center">Last Login: {{last_login}}</h1>
    </div>
  </div>

  <div class="flex justify-end mb-6">
    <!-- <a href="{% url 'main:create_book_entry' %}" class="bg-green-900 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105 mx-4">
      Add New Book Entry
    </a> -->
    <button data-modal-target="crudModal" data-modal-toggle="crudModal" class="btn bg-green-900 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105" onclick="showModal();">
      Add New Book Entry by AJAX
    </button>
  </div>

  <div id="book_entry_cards"></div>
  <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
    <div id="crudModalContent" class="relative bg-white rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">
      <!-- Modal header -->
      <div class="flex items-center justify-between p-4 border-b rounded-t">
        <h3 class="text-xl font-semibold text-gray-900">Add New Book Entry</h3>
        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
          <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
          </svg>
          <span class="sr-only">Close modal</span>
        </button>
      </div>
      <!-- Modal body -->
      <div class="px-6 py-4 space-y-6 form-style">
        <form id="bookEntryForm">
          <div class="mb-4">
            <label for="title" class="block text-sm font-medium text-gray-700">Title</label>
            <input type="text" id="title" name="title" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-green-900" placeholder="Enter book title" required>
          </div>
          <div class="mb-4">
            <label for="author" class="block text-sm font-medium text-gray-700">Author</label>
            <input type="text" id="author" name="author" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-green-900" placeholder="Enter author name" required>
          </div>
          <div class="mb-4">
            <label for="genre" class="block text-sm font-medium text-gray-700">Genre</label>
            <input type="text" id="genre" name="genre" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-green-900" placeholder="Enter book genre" required>
          </div>
          <div class="mb-4">
            <label for="price" class="block text-sm font-medium text-gray-700">Price</label>
            <input type="number" id="price" name="price" class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-green-900" placeholder="Enter price" required>
          </div>
          <div class="mb-4">
            <label for="summary" class="block text-sm font-medium text-gray-700">Summary</label>
            <textarea id="summary" name="summary" rows="3" class="mt-1 block w-full h-52 resize-none border border-gray-300 rounded-md p-2 hover:border-green-900" placeholder="Write a brief summary" required></textarea>
          </div>
        </form>
      </div>
      <!-- Modal footer -->
      <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center md:justify-end">
        <button type="button" class="bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded-lg" id="cancelButton">Cancel</button>
        <button type="submit" id="submitBookEntry" form="bookEntryForm" class="bg-green-900 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded-lg">Save</button>
      </div>
    </div>
  </div>
</div>

<script>
  async function getBookEntries(){
      return fetch("{% url 'main:show_json' %}").then((res) => res.json())
  }

  async function refreshBookEntries() {
    document.getElementById("book_entry_cards").innerHTML = "";
    document.getElementById("book_entry_cards").className = "";
    const bookEntries = await getBookEntries();
    let htmlString = "";
    let classNameString = "";

    if (bookEntries.length === 0) {
      classNameString = "flex flex-col items-center justify-center min-h-[24rem] p-6";
      htmlString = `
        <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
          <img src="{% static 'image/very-sad.png' %}" alt="Sad face" class="w-32 h-32 mb-4"/>
          <p class="text-center text-gray-600 mt-4">No book data available yet.</p>
        </div>
      `;
    } else {
      classNameString = "flex flex-wrap gap-7 w-full";
      bookEntries.forEach((item) => {
        const title = DOMPurify.sanitize(item.fields.title);
        const author = DOMPurify.sanitize(item.fields.author);
        const genre = DOMPurify.sanitize(item.fields.genre);
        const price = DOMPurify.sanitize(item.fields.price);
        const summary = DOMPurify.sanitize(item.fields.summary);

        htmlString += `
          <div class="relative w-64 h-80 bg-white shadow-lg rounded-lg mb-2 border-2 border-gray-300 overflow-hidden flex transform hover:scale-105 hover:shadow-2xl transition-all duration-300">
            <!-- left side -->
            <div class="w-1/5 bg-green-900 text-white p-4 flex flex-col justify-center rounded-l-lg"></div>
            
            <!-- right side -->
            <div class="p-4 flex-1 bg-gray-50 rounded-r-lg flex flex-col">
              <!-- book title -->
              <h3 class="font-bold text-xl text-gray-800 mb-1">${title}</h3>
              <!-- book author -->
              <p class="text-gray-600 italic mb-2">by ${author}</p>
              <!-- book genre -->
              <p class="text-green-700 font-semibold mb-1">Genre: ${genre}</p>
              <!-- book price -->
              <p class="text-green-600 font-bold mb-3">Price: $${price}</p>
              <!-- book summary -->
              <p class="text-gray-700 flex-grow overflow-scroll whitespace-normal text-sm">
                ${summary}
              </p>
              <!-- edit and delete buttons -->
              <div class="flex justify-end space-x-2 mt-2">
                <a href="/edit-book/${item.pk}" class="bg-red-700 hover:bg-red-500 text-white rounded-full p-2 transition duration-300 shadow-md">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                  </svg>
                </a>
                <a href="/delete/${item.pk}" class="bg-red-800 hover:bg-red-600 text-white rounded-full p-2 transition duration-300 shadow-md">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 012 0v6a1 1 11-2 0V8zm5-1a1 1 00-1 1v6a1 1 10 2 0V8a1 1 00-1-1z" clip-rule="evenodd" />
                  </svg>
                </a>
              </div>
            </div>
          </div>
        `;
      });
    }

    document.getElementById("book_entry_cards").className = classNameString;
    document.getElementById("book_entry_cards").innerHTML = htmlString;
  }
  
  refreshBookEntries();

  const modal = document.getElementById('crudModal');
  const modalContent = document.getElementById('crudModalContent');

  function showModal() {
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');

      modal.classList.remove('hidden'); 
      setTimeout(() => {
        modalContent.classList.remove('opacity-0', 'scale-95');
        modalContent.classList.add('opacity-100', 'scale-100');
      }, 50); 
  }

  function hideModal() {
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');

      modalContent.classList.remove('opacity-100', 'scale-100');
      modalContent.classList.add('opacity-0', 'scale-95');

      setTimeout(() => {
        modal.classList.add('hidden');
      }, 150); 
  }

  document.getElementById("cancelButton").addEventListener("click", hideModal);
  document.getElementById("closeModalBtn").addEventListener("click", hideModal);

  function addBookEntry() {
    fetch("{% url 'main:add_book_entry_ajax' %}", {
      method: "POST",
      body: new FormData(document.querySelector('#bookEntryForm')),
    })
    .then(response => refreshBookEntries())

    document.getElementById("bookEntryForm").reset(); 
    document.querySelector("[data-modal-toggle='crudModal']").click();

    return false;
  }

  document.getElementById("bookEntryForm").addEventListener("submit", (e) => {
    e.preventDefault();
    addBookEntry();
  })
</script>

{% endblock content %}